#!/usr/bin/env python3
"""Preprocess the Perigon OpenAPI spec before SDK generation.

This script downloads the public Perigon OpenAPI spec and applies any local
adjustments needed before the SDK is generated by openapi-generator-cli.

Currently it strips ``Article.vectors`` so the field is hidden from the
generated SDK. ``vectors`` is reserved for specific customers and is
temporarily hidden in the public Python SDK. The wrapper-level
``ScoredDataArticle.vectors`` and ``ScoredDataWikiData.vectors`` fields used
by the vector-search endpoints (/v1/vector/news/all, /v1/vector/wikipedia/all)
are intentionally left intact.

Usage:
    poetry run python scripts/preprocess_spec.py

The path of the resulting modified spec file is printed to stdout so the
caller (typically scripts/generate.sh) can pass it directly to
openapi-generator-cli via the ``-i`` flag.
"""

from __future__ import annotations

import json
import sys
import urllib.request
from pathlib import Path
from typing import Any, Dict

SPEC_URL = "https://api.perigon.io/v1/openapi/public-sdk"

# Map of schema name -> property name to remove from that schema.
# Add additional entries here if more fields need to be hidden from the SDK.
PROPERTIES_TO_STRIP: Dict[str, str] = {
    "Article": "vectors",
}

OUT_PATH = Path(__file__).resolve().parent.parent / ".openapi-spec.modified.json"


def fetch_spec(url: str) -> Dict[str, Any]:
    # Some API gateways reject the default urllib user-agent, so set one.
    request = urllib.request.Request(
        url,
        headers={
            "User-Agent": "perigon-python-sdk-generator/1.0",
            "Accept": "application/json",
        },
    )
    with urllib.request.urlopen(request) as resp:
        return json.load(resp)


def strip_properties(spec: Dict[str, Any]) -> None:
    schemas = spec.get("components", {}).get("schemas", {})
    for schema_name, property_name in PROPERTIES_TO_STRIP.items():
        schema = schemas.get(schema_name)
        if not schema:
            print(
                f"warning: schema {schema_name!r} not found in spec; skipping",
                file=sys.stderr,
            )
            continue
        properties = schema.get("properties", {})
        removed = properties.pop(property_name, None)
        if removed is not None:
            print(
                f"stripped {schema_name}.{property_name} from spec",
                file=sys.stderr,
            )
        else:
            print(
                f"note: {schema_name}.{property_name} already absent; nothing to strip",
                file=sys.stderr,
            )

        # Also drop it from `required` if it happens to be listed there.
        required = schema.get("required")
        if isinstance(required, list) and property_name in required:
            required.remove(property_name)
            print(
                f"removed {property_name!r} from {schema_name}.required",
                file=sys.stderr,
            )


def main() -> None:
    print(f"downloading spec from {SPEC_URL}", file=sys.stderr)
    spec = fetch_spec(SPEC_URL)
    strip_properties(spec)
    OUT_PATH.write_text(json.dumps(spec))
    print(f"wrote modified spec to {OUT_PATH}", file=sys.stderr)
    # The path on stdout is consumed by scripts/generate.sh.
    print(OUT_PATH)


if __name__ == "__main__":
    main()
